# Generated by Django 5.0.1 on 2024-03-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuisineName", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("address", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=12)),
                ("openingHours", models.CharField(max_length=128)),
                ("priceRange", models.CharField(max_length=128)),
                ("website", models.URLField()),
                (
                    "cuisine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratearant.cuisine",
                    ),
                ),
            ],
        ),
    ]
