# Generated by Django 5.0.1 on 2024-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratearant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuisine",
            name="id",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="id",
        ),
        migrations.AddField(
            model_name="cuisine",
            name="cuisineID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurantID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
