# Generated by Django 5.0.1 on 2024-03-02 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratearant", "0002_remove_cuisine_id_remove_restaurant_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="cuisine",
        ),
        migrations.DeleteModel(
            name="Cuisine",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
