# Generated by Django 5.0.1 on 2024-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ratearant", "0003_remove_restaurant_cuisine_delete_cuisine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                ("cuisineId", models.AutoField(primary_key=True, serialize=False)),
                ("cuisineName", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
