# Generated by Django 5.0.1 on 2024-03-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratearant", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="restaurant",
            fields=[
                ("restaurantId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("address", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=16)),
                ("website", models.URLField()),
                ("openingTime", models.TimeField()),
                ("priceRange", models.CharField(max_length=16)),
                (
                    "cuisine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratearant.cuisine",
                    ),
                ),
            ],
        ),
    ]
