# Generated by Django 4.1 on 2024-03-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ratearant", "0005_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("reviewId", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("averageScore", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratearant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=128, unique=True)),
                ("password", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("firstName", models.CharField(max_length=128)),
                ("lastName", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foodRating", models.IntegerField()),
                ("serviceRating", models.IntegerField()),
                ("overallRating", models.IntegerField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratearant.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ratearant.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ratearant.user"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("commentId", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ratearant.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ratearant.user"
                    ),
                ),
            ],
        ),
    ]
