# Generated by Django 4.1 on 2024-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratearant", "0006_review_user_score_review_user_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="openingTime",
            field=models.CharField(max_length=30),
        ),
    ]
