# Generated by Django 2.2.26 on 2024-03-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratearant', '0009_auto_20240307_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratearant.Restaurant'),
        ),
    ]
